openapi: 3.2.0
info:
    title: The goakit example downstream service
    description: Archiver is a service that manages the content of HTTP responses
    version: 0.0.1
servers:
    - url: http://localhost:80
      name: archiver
      description: Default server for archiver
paths:
    /archive:
        post:
            tags:
                - archiver
            summary: archive archiver
            description: Archive HTTP response
            operationId: archiver#archive
            requestBody:
                description: Request body for archive.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ArchivePayload'
                        example:
                            body: Neque sunt.
                            status: 200
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GoaArchive'
                            example:
                                body: Rerum rerum aliquid dolores.
                                href: /archive/1
                                status: 200
    /archive/{id}:
        get:
            tags:
                - archiver
            summary: read archiver
            description: Read HTTP response from archive
            operationId: archiver#read
            parameters:
                - name: id
                  in: path
                  description: ID of archive
                  required: true
                  schema:
                    type: integer
                    description: ID of archive
                    example: 1362141423305610375
                    format: int64
                    minimum: 0
                  example: 1557694296985387844
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GoaArchive'
                            example:
                                body: Sit placeat culpa labore eaque.
                                href: /archive/1
                                status: 200
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /health:
        get:
            tags:
                - health
            summary: show health
            description: Health check endpoint
            operationId: health#show
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Voluptatibus omnis sed est.
                            example: Voluptatibus omnis sed est.
components:
    schemas:
        ArchivePayload:
            type: object
            properties:
                body:
                    type: string
                    description: HTTP response body content
                    example: Neque sunt.
                status:
                    type: integer
                    description: HTTP status
                    example: 200
                    format: int64
                    minimum: 0
            description: Request body for archive.
            example:
                body: Neque sunt.
                status: 200
            required:
                - status
                - body
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Error response result type
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GoaArchive:
            type: object
            properties:
                body:
                    type: string
                    description: HTTP response body content
                    example: Consequatur nisi et rerum ipsum accusantium.
                href:
                    type: string
                    description: The archive resouce href
                    example: /archive/1
                    pattern: ^/archive/[0-9]+$
                status:
                    type: integer
                    description: HTTP status
                    example: 200
                    format: int64
                    minimum: 0
            description: Archive is an HTTP response archive
            example:
                body: Consequatur nisi et rerum ipsum accusantium.
                href: /archive/1
                status: 200
            required:
                - href
                - status
                - body
tags:
    - name: archiver
    - name: health
