openapi: 3.2.0
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      name: calculator
      description: Default server for calculator
paths:
    /add:
        post:
            tags:
                - calculator
            summary: add calculator
            description: Add two numbers
            operationId: calculator#add
            requestBody:
                description: Request body for add.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            a: 0.7936796293863132
                            b: 0.05212966980398518
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AddResponseBody'
                            example:
                                operation: In deleniti sint.
                                result: 0.04198102650322011
    /batch/add:
        get:
            tags:
                - calculator
            summary: batch_add calculator
            description: Add multiple pairs of numbers using streaming
            operationId: calculator#batch_add
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchAddResponseBody'
                            example:
                                index: 312737943510911382
                                result: 0.8965135098234011
    /divide:
        post:
            tags:
                - calculator
            summary: divide calculator
            description: Divide two numbers
            operationId: calculator#divide
            requestBody:
                description: Request body for divide.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DivideRequestBody'
                        example:
                            dividend: 0.5184906879153129
                            divisor: 0.5616730288110641
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AddResponseBody'
                            example:
                                operation: Nesciunt consequatur consectetur cupiditate sit.
                                result: 0.08459169404214541
                "400":
                    description: 'division_by_zero: Cannot divide by zero'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculatorError'
                            example:
                                code: Dignissimos ut voluptate fuga minus vero omnis.
                                message: Repellendus quidem eligendi voluptas quae eius.
    /factorial:
        post:
            tags:
                - calculator
            summary: factorial calculator
            description: Calculate factorial of a number
            operationId: calculator#factorial
            requestBody:
                description: Request body for factorial.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FactorialRequestBody'
                        example:
                            "n": 10
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FactorialResponseBody'
                            example:
                                computation_time_ms: 7430406659417736888
                                operation: In quo.
                                result: 2802676607681044054
                "400":
                    description: 'invalid_input: Input must be between 0 and 20'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculatorError'
                            example:
                                code: Laborum laudantium delectus illo explicabo.
                                message: Nobis ea.
    /statistics:
        post:
            tags:
                - calculator
            summary: statistics calculator
            description: Calculate statistics for a list of numbers
            operationId: calculator#statistics
            requestBody:
                description: Request body for statistics.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/StatisticsRequestBody'
                        example:
                            numbers:
                                - 0.5842830148544397
                                - 0.6757557090818312
                                - 0.3604039578340141
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StatisticsResponseBody'
                            example:
                                count: 7525631923450415662
                                max: 0.9702023620235123
                                mean: 0.3176589236328283
                                median: 0.5259699852027079
                                min: 0.4948460127995459
                                sum: 0.7469671830093337
                "400":
                    description: 'empty_list: List cannot be empty'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculatorError'
                            example:
                                code: Non aut expedita soluta ratione maiores.
                                message: Velit doloribus.
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                a:
                    type: number
                    description: First number
                    example: 0.7936796293863132
                    format: double
                b:
                    type: number
                    description: Second number
                    example: 0.05212966980398518
                    format: double
            description: Request body for add.
            example:
                a: 0.7936796293863132
                b: 0.05212966980398518
            required:
                - a
                - b
        AddResponseBody:
            type: object
            properties:
                operation:
                    type: string
                    description: Operation performed
                    example: In deleniti sint.
                result:
                    type: number
                    description: Sum of a and b
                    example: 0.04198102650322011
                    format: double
            example:
                operation: In deleniti sint.
                result: 0.04198102650322011
            required:
                - result
                - operation
        BatchAddResponseBody:
            type: object
            properties:
                index:
                    type: integer
                    description: Operation index
                    example: 312737943510911382
                    format: int64
                result:
                    type: number
                    description: Sum
                    example: 0.8965135098234011
                    format: double
            example:
                index: 312737943510911382
                result: 0.8965135098234011
            required:
                - result
                - index
        CalculatorError:
            type: object
            properties:
                code:
                    type: string
                    description: Error code
                    example: Dignissimos ut voluptate fuga minus vero omnis.
                message:
                    type: string
                    description: Error message
                    example: Repellendus quidem eligendi voluptas quae eius.
            description: Cannot divide by zero
            example:
                code: Dignissimos ut voluptate fuga minus vero omnis.
                message: Repellendus quidem eligendi voluptas quae eius.
            required:
                - message
                - code
        DivideRequestBody:
            type: object
            properties:
                dividend:
                    type: number
                    description: Number to divide
                    example: 0.5184906879153129
                    format: double
                divisor:
                    type: number
                    description: Number to divide by
                    example: 0.5616730288110641
                    format: double
            description: Request body for divide.
            example:
                dividend: 0.5184906879153129
                divisor: 0.5616730288110641
            required:
                - dividend
                - divisor
        FactorialRequestBody:
            type: object
            properties:
                "n":
                    type: integer
                    description: Number to calculate factorial of
                    example: 10
                    format: int64
                    minimum: 0
                    maximum: 20
            description: Request body for factorial.
            example:
                "n": 10
            required:
                - "n"
        FactorialResponseBody:
            type: object
            properties:
                computation_time_ms:
                    type: integer
                    description: Time taken in milliseconds
                    example: 7430406659417736888
                    format: int64
                operation:
                    type: string
                    description: Operation performed
                    example: In quo.
                result:
                    type: integer
                    description: Factorial result
                    example: 2802676607681044054
                    format: int64
            example:
                computation_time_ms: 7430406659417736888
                operation: In quo.
                result: 2802676607681044054
            required:
                - result
                - operation
                - computation_time_ms
        StatisticsRequestBody:
            type: object
            properties:
                numbers:
                    type: array
                    items:
                        type: number
                        example: 0.858415483142481
                        format: double
                    description: List of numbers
                    example:
                        - 0.5842830148544397
                        - 0.6757557090818312
                        - 0.3604039578340141
                    minItems: 1
            description: Request body for statistics.
            example:
                numbers:
                    - 0.5842830148544397
                    - 0.6757557090818312
                    - 0.3604039578340141
            required:
                - numbers
        StatisticsResponseBody:
            type: object
            properties:
                count:
                    type: integer
                    description: Number of values
                    example: 7525631923450415662
                    format: int64
                max:
                    type: number
                    description: Maximum value
                    example: 0.9702023620235123
                    format: double
                mean:
                    type: number
                    description: Average of numbers
                    example: 0.3176589236328283
                    format: double
                median:
                    type: number
                    description: Median value
                    example: 0.5259699852027079
                    format: double
                min:
                    type: number
                    description: Minimum value
                    example: 0.4948460127995459
                    format: double
                sum:
                    type: number
                    description: Sum of all values
                    example: 0.7469671830093337
                    format: double
            example:
                count: 7525631923450415662
                max: 0.9702023620235123
                mean: 0.3176589236328283
                median: 0.5259699852027079
                min: 0.4948460127995459
                sum: 0.7469671830093337
            required:
                - mean
                - median
                - min
                - max
                - count
                - sum
tags:
    - name: calculator
      description: A simple calculator service to demonstrate testing plugin features
